[package]
name = "par-dialog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
fuzzy-matcher = "0.3"
ratatui = "0.27"
tracing = { workspace = true }
